### PR TITLE
Implement Christopher's suggestions in pull request #68

### PR DESCRIPTION
**Pull request by csyhuang**
Christopher,

Great thanks for the changes and suggestions you've made! I learned something new! I think all of your suggestions are thoughtful so I implemented all of them. Now, there is no redundant arguments in QGFieldNH18. `eq_boundary_index` is an argument specific to QGFieldNHN22. As you anticipate, some parts of QGDataset breaks due to the refactoring to QGField subclasses.

On top of fixing QGDataset, there are a few spots which I need your help in fixing:
- I included two integration tests to check the output values of `QGFieldNH18` and `QGFieldNHN22` as used in `demo_script_for_nh2018.ipynb`: 
  - All unit tests passed on my local machine, but failed when GitHub runs the workflow(It is due to an error when using xarray to read netCDF, but I don't encounter this on my machine). May you run on your machine to see if any tests break?
  - I did not include a check in flux term values because they seem not stable - tests passed and failed from time to time even when I increase the relative tolerance `rtol` in `np.allclose` check. Nevertheless, for this release, fixing this would be of low priority. Let's wait till we verify the merge of the flux computation interface.
- The demo notebook `notebooks/nh2018_science/demo_script_for_nh2018.ipynb` is working fine but its QGDataset counterpart `notebooks/nh2018_science/demo_script_for_nh2018_with_xarray.ipynb` does not produce the correct `Advective flux convergence` and `divergence of eddy momentum flux` plot. May you look into it?

I will be traveling few hours later and will not be able to access my computer (but still can check email) until Monday evening. Given that there may be more changes needed for this release, let's use the branch `release0.7.0` for development and merge back to `master` once all components are ready? If you approve this pull request, may you help merging the commits to `release0.7.0`?

For the suggested work in #66, may you submit a pull request to `release0.7.0`? If time is not enough, please prioritize fixing the Xarray interface. We can worry about the notebooks later. 

Thanks a lot for offering to take care of these!

All the best,

Clare

### CODE REVIEW

**Comment by chpolste** [comment]
Hi Clare,

I'm happy to merge `release0.7.0-value-check`, but we can merge directly to `release0.7.0`, I think. I'll take care of that tomorrow. I've begun working on the xarrayinterface starting from the value-check branch and need a bit more time to finish up. I'll look into the problem with the values in the notebook and see if I find the time for #66 this week.

Running the unit tests locally, I see two failures:
```
FAILED tests/test_output_results.py::test_expected_value_check_nh18 - AssertionError: lwa values don't match
FAILED tests/test_output_results.py::test_expected_value_check_nhn22 - TypeError: matrix_b4_inversion.matrix_b4_inversion() missing required argument 'tjk' (pos 15)
```
This is Python 3.9.7 with xarray 0.20.1.

Best,
Christopher

**Comment by csyhuang** [comment]
Hi @chpolste 

Merging directly to `release0.7.0` would work too. Thanks for taking care of this!

For the two local unit test failure you encountered, looks like the compiled f2py modules in your machine is not the most updated ones. May you remove all the `.so` files, recompile (maybe via `python setup.py develop`) and rerun the unit test?

if you check the Workflow from GitHub:
https://github.com/csyhuang/hn2016_falwa/actions/runs/5100655322/jobs/9169064029
The setup for tests in `test_output_results.py` is failing with the following errors:
```
  self._add_data_files(self._safe_data_files(build_py))

    @pytest.fixture(scope="module")
    def u_field():
        """
        Return u field arranged in ascending order in latitude and height from 2005-01-23 00:00
        """
>       u_file = xr.open_dataset(f"{test_data_dir}/2005-01-23-0000-u.nc")

tests/test_output_results.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/xarray/backends/api.py:479: in open_dataset
    engine = plugins.guess_engine(filename_or_obj)
/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/xarray/backends/plugins.py:107: in guess_engine
    engines = list_engines()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    @functools.lru_cache(maxsize=1)
    def list_engines():
>       entrypoints = entry_points().get("xarray.backends", ())
E       AttributeError: 'EntryPoints' object has no attribute 'get'
```

I never observed it on my machine, and seems you didn't encounter this either (if your test can go straight to checking `lwa` values). If we cannot find a way to fix Git Workflow, perhaps we can skip `test_output_results.py` in deployment procedure since it's mainly for development purpose.

Please keep me updated how the unit tests behave after you pull the latest changes and recompile the f2py modules.

Thanks!

Clare

**Comment by chpolste** [comment]
You're right, I did have a mixup with the installation and older Fortran modules. Now both tests fail with "lwa values don't match":

```
FAILED tests/test_output_results.py::test_expected_value_check_nh18 - AssertionError: lwa values don't match
FAILED tests/test_output_results.py::test_expected_value_check_nhn22 - AssertionError: lwa values don't match
```

As you say, I don't seem to encounter the EntryPoints problem locally either.

**Comment by chpolste** [comment]
I'll merge for now and we can sort out the unit test issue before merging into master.

**Pull request merged**
