### PR TITLE
Add pyproject.toml

### PR DESCRIPTION
**Pull request by chpolste**
Python appears to be moving away from the `setup.py`, so in the attached commit I tried to convert the `setup.py` to a `pyproject.toml`. I can get the package to install (incl. the `.so` files) locally, but it's my first time writing one so something will probably be missing or not properly configured. In particular, I haven't figured out how to compile extensions outside of `setup.py` and how to set development dependencies so they are picked up by the CI.

We could iterate in this PR to figure these issues out.

### CODE REVIEW

**Comment by csyhuang** [comment]
Hi Christopher, thanks for submitting this pull request. I haven't got time to research into methods for compiling f2py with this adjustment yet, so let's do this in a future release. Let's keep this PR active.

**Comment by chpolste** [comment]
[This stackoverflow post](https://stackoverflow.com/a/66479252) is quite informative about compiling extensions with a pyproject.toml. It suggests that keeping a setup.py around for building extensions is part of the process. The [setuptools docs](https://setuptools.pypa.io/en/latest/userguide/ext_modules.html) seem to suggest the same.

I'll revisit this pull request in time for the 0.7.3 release.

**Comment by csyhuang** [comment]
@chpolste Sorry I accidentally deleted release1.0 branch such that this ticket is automatically closed. I have updated the branch `pyproject-toml` and wonder if this PR can be reopen?

**Comment by csyhuang** [comment]
Sorry I accidentally deleted release1.0 branch such that this ticket is automatically closed. I have updated the branch pyproject-toml and wonder if this PR can be reopen?

**Pull request closed without merging**
